In [14]:
from pandas import Series, DataFrame
import pandas as pd
orig_data = pd.read_csv('Data/Train_rev1.csv',
                        dtype=unicode)

In [15]:
orig_data

,Id,Title,FullDescription,LocationRaw,LocationNormalized,ContractType,ContractTime,Company,Category,SalaryRaw,SalaryNormalized,SourceName
0,12612628,Engineering Systems Analyst,Engineering Systems Analyst Dorking Surrey Sal...,"Dorking, Surrey, Surrey",Dorking,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 30000/annum 20-30K,25000,cv-library.co.uk
1,12612830,Stress Engineer Glasgow,Stress Engineer Glasgow Salary **** to **** We...,"Glasgow, Scotland, Scotland",Glasgow,NaN,permanent,Gregory Martin International,Engineering Jobs,25000 - 35000/annum 25-35K,30000,cv-library.co.uk
2,12612844,Modelling and simulation analyst,Mathematical Modeller / Simulation Analyst / O...,"Hampshire, South East, South East",Hampshire,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 40000/annum 20-40K,30000,cv-library.co.uk
3,12613049,Engineering Systems Analyst / Mathematical Mod...,Engineering Systems Analyst / Mathematical Mod...,"Surrey, South East, South East",Surrey,NaN,permanent,Gregory Martin International,Engineering Jobs,25000 - 30000/annum 25K-30K negotiable,27500,cv-library.co.uk
4,12613647,"Pioneer, Miser Engineering Systems Analyst","Pioneer, Miser Engineering Systems Analyst Do...","Surrey, South East, South East",Surrey,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 30000/annum 20-30K,25000,cv-library.co.uk
5,13179816,Engineering Systems Analyst Water Industry,Engineering Systems Analyst Water Industry Loc...,"Dorking, Surrey, Surrey, Surrey",Dorking,NaN,permanent,Gregory Martin International,Engineering Jobs,20000 - 30000/annum 20K to 30K,25000,cv-library.co.uk
6,14131336,Senior Subsea Pipeline Integrity Engineer,A globally renowned engineering and training c...,"Aberdeen, Borders",UK,NaN,permanent,Indigo 21 Ltd,Engineering Jobs,50000 - 100000/annum,75000,cv-library.co.uk
7,14663196,RECRUITMENT CONSULTANT INDUSTRIAL / COMMERCIA...,THIS IS A LIVE VACANCY NOT A GENERIC ADVERTISE...,"MANCHESTER, Greater Manchester",Manchester,NaN,permanent,Code Blue Recruitment,HR & Recruitment Jobs,18000 - 26000/annum TO 26K BASIC + COMM + BENS,22000,cv-library.co.uk
8,14663197,RECRUITMENT CONSULTANT CONSTRUCTION / TECHNIC...,This is an exceptional opportunity to join a c...,"LEEDS, West Yorkshire",Leeds,NaN,permanent,Code Blue Recruitment,HR & Recruitment Jobs,18000 - 28000/annum 18 - 28K BASIC + COMM + BENS,23000,cv-library.co.uk
9,15395797,Subsea Cables Engineer,A subsea engineering company is looking for an...,"Aberdeen, UK",Aberdeen,NaN,permanent,Indigo 21 Ltd,Engineering Jobs,70000 - 100000/annum,85000,cv-library.co.uk
10,19047429,Trainee Mortgage Advisor East Midlands,"Are you a successful, results driven person? A...",East Midlands,East Midlands,NaN,permanent,Brite Recruitment,Accounting & Finance Jobs,17000 - 25000/annum 17k - 20k OTE 25k,21000,cv-library.co.uk
11,20199757,"PROJECT ENGINEER, PHARMACEUTICAL","PROJECT ENGINEER PHAMACEUTICAL, c**** Excelle...","Witney, Oxfordshire",Witney,NaN,permanent,MatchBox Recruiting Ltd,Healthcare & Nursing Jobs,35000 - 40000/annum c40000 + Excellent Benefits,37500,cv-library.co.uk
12,20638787,Principal Composite Stress Engineer,Aerospace Senior Composite Structures Engineer...,"Avon, South West",Avon,NaN,permanent,Gregory Martin International,Other/General Jobs,40000 - 50000/annum 40K-50K,45000,cv-library.co.uk
13,20638788,Senior Fatigue Damage Tolerance Engineer,Senior Fatigue Static stress (metallic or comp...,"Avon, South West",Avon,NaN,permanent,Gregory Martin International,Other/General Jobs,35000 - 45000/annum 35K-45K,40000,cv-library.co.uk
14,20797143,Chef de Partie Award Winning Restaurant Exce...,A well respected restaurant located in the Der...,Derby Derbyshire East Midlands,Derby,NaN,NaN,Chef Results,Hospitality & Catering Jobs,"Upto 16,000 per annum + Tips (IRO 3K Per Annum)",16000,caterer.com
15,22579462,Quality Engineer,Our client are a leading supplier of precision...,"Gateshead, Tyne and Wear",Gateshead,NaN,permanent,Asset Appointments,Engineering Jobs,22000/annum,22000,cv-library.co.uk
16,22581547,Principal Controls Engineer,A leading Subsea Engineering Company require a...,"Kent, South East",Kent,NaN,permanent,Indigo 21 Ltd,Engineering Jobs,70000 - 100000/annum,85000,cv-library.co.uk
17,22933091,Chef de Partie Award Winning Dining Live In ...,A popular hotel located in Norfolk which is a ...,Norfolk East Anglia,UK,NaN,NaN,Chef Results,Hospitality & Catering Jobs,"18,000 per annum + Tips (IRO 120 Per Month)",18000,caterer.com
18,23528672,Senior Fatigue and Damage Tolerance Engineer,Senior Fatigue Static stress (metallic or comp...,"Avon, South West",Avon,NaN,permanent,Gregory Martin International,Engineering Jobs,34000 - 45000/annum to 45K,39500,cv-library.co.uk
19,23529949,C I Design Engineer,We are currently recruiting on behalf of our c...,"Wolverhampton, West Midlands",Wolverhampton,NaN,permanent,Rullion Engineering Ltd,Engineering Jobs,33000 - 34000/annum + benefits,33500,cv-library.co.uk
20,23530231,Lead Engineers (Stress),Lead Engineers (Stress) Our client provide hig...,"Bristol, Avon, South West, Avon",UK,NaN,permanent,Gregory Martin International,Engineering Jobs,34000 - 45000/annum,39500,cv-library.co.uk
21,24104334,"Relief Chef de Partie Croydon, Surrey Live in",HOTEL AND CONFERENCE VENUE CHAIN RELIEF CHEF...,South Croydon Surrey South East,UK,NaN,NaN,Towngate Personnel,Hospitality & Catering Jobs,Upto 9 per hour,17280,caterer.com
22,24835524,Senior Control and Instrumentation Engineer,Senior Control and Instrumentation Engineer . ...,"Berkshire, South East",Berkshire,NaN,permanent,Gregory Martin International,Engineering Jobs,36000 - 47000/annum 36K-47K,41500,cv-library.co.uk
23,24835548,Control and Instrumentation Engineer,Control and Instrumentation Engineer / C Readi...,"Berkshire, South East",Berkshire,NaN,permanent,Gregory Martin International,Engineering Jobs,28000 - 35000/annum 28K-35K,31500,cv-library.co.uk
24,24854800,Electrical / ICA Engineer,Electrical / ICA Engineer Industry: Environmen...,"Surrey, South East",Surrey,NaN,permanent,Gregory Martin International,Engineering Jobs,"28000 - 37000/annum 28,000 to 37,000",32500,cv-library.co.uk
25,25337172,Pastry Chef for **** red star **** rosette hot...,Pastry Chef for **** red star **** rosette hot...,North East,North East England,NaN,NaN,Clear Selection,Hospitality & Catering Jobs,24000 per annum,24000,caterer.com
26,25434785,Senior Process Engineer,Senior Process Engineer We are seeking applica...,"Berkshire, South East",Berkshire,NaN,permanent,Gregory Martin International,Engineering Jobs,36000 - 47000/annum 36-47K,41500,cv-library.co.uk
27,25452606,CHEF DE PARTIE POSITION IN **** ROSETTE HOTEL ...,CHEF DE PARTIE POSITION IN **** ROSETTE HOTEL ...,North Yorkshire Yorkshire,North Yorkshire,NaN,NaN,Clear Selection,Hospitality & Catering Jobs,16000 per annum + Live In,16000,caterer.com
28,25452680,"Senior Sous Chef for **** rosette kitchen, up ...","Senior Sous Chef for **** rosette kitchen, up ...",North East,North East England,NaN,NaN,Clear Selection,Hospitality & Catering Jobs,26000 per annum,26000,caterer.com
29,25556432,"General Manager Funky, Cool Restaurant Concep...","Senior General Manager – Funky, Cool, Casual R...",West London London South East,East Sheen,NaN,NaN,Bee Recruitment London Ltd,Hospitality & Catering Jobs,"From 28,000 to 35,000 per annum",31500,caterer.com
...,...,...,...,...,...,...,...,...,...,...,...,...
244738,72703385,Payroller,NEED PAYROLLERS WITH ESR WHO HAVE WORKED AT PR...,London,London,NaN,contract,NaN,Other/General Jobs,"28,000",28000,hays.co.uk
244739,72703387,Commercial Account Manager,Commercial Account Manager Role An opportunity...,London,London,NaN,permanent,NaN,Other/General Jobs,"47,000 - 65,000",56000,hays.co.uk
244740,72703405,Salaried GP,At DMC Healthcare we believe the delivery of e...,South London SE15,South Bermonsey,full_time,permanent,DMC Healthcare,Healthcare & Nursing Jobs,70K + (DOE),70000,jobs.gponline.com
244741,72703407,HR Ops Manager (North Region),My retail client are currently recruiting for ...,Manchester,Manchester,NaN,permanent,NaN,Scientific & QA Jobs,"35,000 - 42,000 DOE",38500,hays.co.uk
244742,72703410,Legal Cashier,LEGAL CASHIER JOB. A top Legal firm based in C...,London,London,NaN,contract,NaN,Legal Jobs,18- 20 per hour,36480,hays.co.uk
244743,72703415,Postroom Operator,A prestigious chambers (Law firm) in the City ...,Temple,Temple,NaN,permanent,NaN,Legal Jobs,"19,000",19000,hays.co.uk
244744,72703423,Senior Business Travel Consultant Birmingham,Are you an experienced senior business travel ...,Birmingham,Birmingham,full_time,permanent,Travel Trade Recruitment,Travel Jobs,17000 - 18800 per annum + Fantastic Company!,17900,jobs.travelweekly.co.uk
244745,72703429,Salaried General Practitioners,Full and parttime opportunities available With...,Hampshire-wide,UK,NaN,NaN,Care UK,Healthcare & Nursing Jobs,up to 100k pa plus MDU plus relocation negotiable,100000,jobs.gponline.com
244746,72703432,"Salaried GP, Essex, 4 days per week, ****k NH...","Salaried GP needed in Essex, 4 days per week. ...","Essex, South East",UK,full_time,permanent,Global Medics Permanent UK,Healthcare & Nursing Jobs,"Up to 81k, 4 days per week + NHS Pension + MDU",81000,jobs.gponline.com
244747,72703435,Long Haul Travel Consultant Staffordshire,Are you a Travel Consultant who is truly passi...,Staffordshire,Staffordshire,full_time,permanent,Travel Trade Recruitment,Travel Jobs,13000 - 17000 per annum + Fantastic company an...,15000,jobs.travelweekly.co.uk
244748,72703444,Home Working Cruise Consultant,"Travel Consultants, we have an amazing opportu...",West Midlands,West Midlands,full_time,permanent,Travel Trade Recruitment,Travel Jobs,15000 per annum + Excellent Uncapped OTE!,15000,jobs.travelweekly.co.uk
244749,72703454,Personal Travel Expert Luxury Travel,PERSONAL TRAVEL EXPERT Location Birmingham Sa...,Birmingham,Birmingham,full_time,permanent,AA Appointments,Travel Jobs,18000 - 22000 per annum + competitive,20000,jobs.travelweekly.co.uk
244750,72703459,Senior Business Travel Consultant Birmingham,Are you an experienced Senior Business Travel ...,Birmingham,Birmingham,full_time,permanent,Travel Trade Recruitment,Travel Jobs,17000 - 21000 per annum + Fantastic Company!,19000,jobs.travelweekly.co.uk
244751,72703748,Data Architect,A vibrant charitable institute based in Kensin...,London,London,NaN,permanent,NaN,Charity & Voluntary Jobs,Up to 40k,40000,hays.co.uk
244752,72705197,Curriculum Leader Mathematics,Curriculum Leader Mathematics TLR 1 **** Requi...,Wrexham,Wrexham,NaN,permanent,NaN,Teaching Jobs,"MPS plus TLR 1 9,013",5006,hays.co.uk
244753,72705199,TEACHER OF MATHS,Position: Qualified Teacher Subject/Specialism...,Wiltshire,Wiltshire,NaN,contract,NaN,Teaching Jobs,450 to $500 per week,22800,hays.co.uk
244754,72705200,Marketing Officer Job,Marketing Officer Job Use a broad range of Mar...,Southampton,Southampton,NaN,permanent,NaN,Teaching Jobs,"27,000 - 33,000 DoE plus attractive benefits",30000,hays.co.uk
244755,72705201,ENGLISH TEACHER,Position: Qualified Teacher Subject/Specialism...,Wiltshire,Wiltshire,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244756,72705202,COVER SUPERVISOR,Position: Cover Supervisor Subject/Specialism:...,Wiltshire,Wiltshire,NaN,contract,NaN,Teaching Jobs,300 to 350 per week,15600,hays.co.uk
244757,72705203,TEACHER OF BUSINESS STUDIES AND LAW,Position: Qualified Teacher Subject/Specialism...,Salisbury,Salisbury,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244758,72705204,SUPPLY TEACHERS,Position: Qualified Teacher Subject/Specialism...,Salisbury,Salisbury,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244759,72705205,TEACHER OF BUSINESS STUDIES AND ICT,Position: Qualified Teacher Subject/Specialism...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 - 500 per week,22800,hays.co.uk
244760,72705207,HISTORY TEACHER,Position: Teacher Subject/Specialism: History ...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244761,72705208,TEACHER OF SCIENCE,Position: Qualified Teacher Subject/Specialism...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244762,72705209,TEACHER OF ENGLISH,Position: Qualified Teacher Subject/Specialism...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244763,72705211,TEACHER OF SCIENCE,Position: Qualified Teacher Subject/Specialism...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 - 500 per week,22800,hays.co.uk
244764,72705212,TEACHER OF BUSINESS STUDIES AND ICT,Position: Qualified Teacher or NQT Subject/Spe...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 - 500 per week,22800,hays.co.uk
244765,72705213,ENGLISH TEACHER,Position: Qualified Teacher Subject/Specialism...,Swindon,Swindon,NaN,contract,NaN,Teaching Jobs,450 - 500 per week,22800,hays.co.uk
244766,72705216,SUPPLY TEACHERS,Position: Qualified Teacher Subject/Specialism...,Wiltshire,Wiltshire,NaN,contract,NaN,Teaching Jobs,450 to 500 per week,22800,hays.co.uk
244767,72705235,Accountant,This entrepreneurial and growing private equit...,Hitchin,Hitchin,NaN,permanent,NaN,Teaching Jobs,"40-45,000",42500,hays.co.uk

In [16]:
jobs_sample = orig_data.sample(1000)

In [17]:
jobs_sample

,Id,Title,FullDescription,LocationRaw,LocationNormalized,ContractType,ContractTime,Company,Category,SalaryRaw,SalaryNormalized,SourceName
82810,69042381,Testing Coordinator,Leading software Integration Company is proact...,London South East,South East London,NaN,permanent,C4 Commerce,IT Jobs,"From 35,000 to 40,000 per annum PACKAGE",37500,cwjobs.co.uk
183438,71624825,Business Account Manager,Working for a well established Mailing based o...,City of Edinburgh - Juniper Green,UK,full_time,permanent,UKStaffsearch,Customer Services Jobs,18000 - 20000,19000,ukstaffsearch.com
153686,70809071,WAREHOUSE OPERATIVE,To work as part of a team of Warehouse operati...,Lutterworth,Lutterworth,full_time,NaN,Prime Time Recruitment,Manufacturing Jobs,6.50 - 6.61 per hour,12585,Jobcentre Plus
116089,69777189,Multi Skilled Shift Engineer,Demob Job Reference: j**** Job Title: Multi Sk...,"Wellington, Somerset",Wellington,NaN,permanent,Demob Job,Engineering Jobs,"25631/annum 25,631.82",25631,cv-library.co.uk
92351,69173550,Senior EIA Consultant Edinburgh,Senior EIA Consultant Edinburgh My client is ...,Edinburgh Midlothian Scotland,Edinburgh Technopole,NaN,permanent,Penguin Recruitment,Scientific & QA Jobs,30000 - 35000 per annum + benefits,32500,totaljobs.com
188532,71692970,Campaign Marketing Manager Retail,CAMPAIGN MARKETING MANAGER RETAIL SALARY ***...,Sheffield South Yorkshire Yorkshire,Sheffield,NaN,permanent,Discover Retail Ltd,Retail Jobs,25000 - 28000 per annum + benefits,26500,retailchoice.com
164562,71275601,HEAD CHEF OXFORDSHIRE VILLAGE PUB (FREE LIVE IN),HEAD CHEF NORTH OXFORDSHIRE BANBURY FREE LIVE ...,Banbury Oxfordshire South East,Banbury,NaN,NaN,Goldstar Recruitment,Hospitality & Catering Jobs,"From 20,000 to 24,000 per annum + LIVE IN",22000,caterer.com
132062,70210397,Pensions Valuation Accountant,Highly challenging international role where yo...,Berkshire,Berkshire,NaN,permanent,Sammons Pensions,Accounting & Finance Jobs,GBP38000 - 41000 per annum,39500,professionalpensionsjobs.com
82524,69040286,Business Solutions Architect Oracle ERP,Business Solutions Architect Oracle ERP A lea...,Buckinghamshire South East,Buckinghamshire,NaN,permanent,Spectrum IT Recruitment Ltd,IT Jobs,80000 - 90000 per annum,85000,cwjobs.co.uk
151987,70770693,Developer,Capita Plc is the UKs leading business process...,"Newbury, Berkshire",Newbury,NaN,permanent,Capita Resourcing,IT Jobs,25000 - 28000/annum NA,26500,cv-library.co.uk
173382,71430396,Employer Partnership Coordinator,When you join Ingeus as an Employer Partnershi...,West London London South East,East Sheen,NaN,permanent,Ingeus,HR & Recruitment Jobs,29420 per annum + excellent benefits,29420,totaljobs.com
106502,69591871,B2B Account Executive,"Our Client, a leading US technology marketing ...",Belfast,Belfast,NaN,permanent,ARRAY,HR & Recruitment Jobs,"19000 - 23000, basic",21000,recruitni.com
119321,69852686,Trainee Sales Assistant Film Game Packages,Trainee Sales Assistant Film Game Packages R...,"Chelmsford, Rayleigh, Witham, Braintree, Bille...",UK,NaN,NaN,J30,Retail Jobs,250-450 weekly (OTE),16800,jobsite.co.uk
23841,67448183,Electronic Engineering Lecturer,We require a Lecturer with relevant up to date...,Bridgend,Bridgend,full_time,NaN,NaN,Teaching Jobs,18.00 - 25.00 per hour,41280,Jobcentre Plus
196396,71814787,Audit and Investigation Officer,Ready to take on a new challenge? The Royal Bo...,Maidenhead,Maidenhead,full_time,permanent,Royal Borough of Windsor Maidenhead,Accounting & Finance Jobs,"31,795 - 35,255 pa",33525,careersinaudit.com
66941,68715169,Purchase Ledger Assistant (maternity cover),Fantastic opportunity for an experienced Purch...,Bicester Oxfordshire South East,Bicester,NaN,permanent,Hays,Retail Jobs,22000.00 - 25000.00 per annum,23500,totaljobs.com
175630,71445033,Graduate Software Support Analyst,Graduate Software Support Analyst London **** ...,London,London,NaN,permanent,Informatiq Consulting Limited,IT Jobs,"25,000 + Bonus + Benefits",25000,jobsite.co.uk
158598,71141855,Relief General Assistant (NPLQ),RELIEF GENERAL ASSISTANT (NPLQ) Ref: L**** ***...,Belfast,Belfast,NaN,permanent,ARRAY,HR & Recruitment Jobs,6.29 - 7.63 p/h,13363,recruitni.com
15785,66770410,Business Development Manager,Business Development Manager Hospitality Busi...,"Lancashire, North West",Lancashire,NaN,permanent,NaN,Retail Jobs,"30000 per annum + 50k OTE,laptop,mobile,compan...",40000,jobs.telegraph.co.uk
84813,69079397,Test Debug Technician,"Job Title: Test s, it would be beneficial for ...","Chesham, Buckinghamshire",Chesham,NaN,contract,Orion Electrotech,Engineering Jobs,10 - 13/hour shift allowance,22080,cv-library.co.uk
63882,68705464,Contracts and Compliance Officer Asbestos,New position Following a recent reorganisation...,St. Asaph Clwyd Wales,UK,NaN,permanent,Supertemps,Trade & Construction Jobs,"21,520 - 24,647 per year + excellent benefits",23083,totaljobs.com
11396,66536888,Handyman,Search Construction requires ONE Handyman for ...,Seaford,Seaforde,full_time,NaN,Search Consultancy,Trade & Construction Jobs,9.00 per hour,17280,Jobcentre Plus
88303,69139347,Net / Front End / Ektron,I am looking for a .Net developer with experie...,"Greater London, Central London, South East Eng...",London,NaN,NaN,Computer Futures,Other/General Jobs,"75,000-99,999 yearly",87499,theladders.co.uk
17035,66906376,System Analyst,Excellent opportunity for a System Analyst to ...,Edinburgh,Edinburgh,NaN,contract,NaN,Accounting & Finance Jobs,175 per day,42000,hays.co.uk
105089,69576292,Internet Security Software Engineer Cambridge...,Internet Security Software Engineer Cambridge...,Cambridgeshire - Cambridge,Cambridge,full_time,permanent,CVbrowser,IT Jobs,45000 - 55000,50000,cvbrowser.com
89800,69158506,"Remedy Support Consultants Portsmouth, Up to ...",Our client a major BMC partner are looking to ...,Hampshire Portsmouth PO1 1,Hayling Island,NaN,permanent,Excel Resourcing Solutions,IT Jobs,40000.00 GBP Annual,40000,jobserve.com
209758,72174109,IT Delivery Consultant,"My client, one of the world's leading speciali...",City,The City,NaN,permanent,NaN,HR & Recruitment Jobs,30k - 40k,35000,careersinrecruitment.com
133831,70251180,International Sales & Marketing Manager,Elevation Sales Marketing are currently recrui...,Leeds West Yorkshire Yorkshire,Leeds,NaN,permanent,elevation sales,Sales Jobs,50000 - 55000 per annum + Car + Bonus + Bens,52500,totaljobs.com
240333,72637276,German Customer Service Agent in Belfast,Responsibilities Handle inbound and outbound G...,"Belfast, Northern Irel",UK,NaN,contract,mgi recruitment,Customer Services Jobs,20000 - 24000,22000,Multilingualvacancies
69922,68807391,"Sales Executive / Account Manager, FMCG Global...","Sales Executive / Account Manager, FMCG Global...","Brighton,Worthing,Burgess Hill,Haywards Heath,...",UK,NaN,permanent,Aaron Wallis Recruitment Training Ltd,Sales Jobs,26840 + Bonus + Car,26840,jobsite.co.uk
...,...,...,...,...,...,...,...,...,...,...,...,...
161799,71194732,Technical Author,"Introduction Our client, a leading water secto...",Peterborough,Peterborough,NaN,NaN,Matchtech Group plc.,Engineering Jobs,24 - 27/hr,48960,rengineeringjobs.com
3387,58244316,Experienced Category C (HGV II) Drivers,We have on going Class 2 palletised multidrop ...,"Eye, Kings Lynn,Norwich, Wisbech Thetford, Fak...",UK,part_time,NaN,Contract Personnel Limited,Logistics & Warehouse Jobs,7.50 - 11.50/hour Holiday Pay,18240,cv-library.co.uk
69384,68805764,PROJECT PLANNER,PROJECT PLANNER CONTRACTS 6 MONTHS BASINGSTO...,Basingstoke,Basingstoke,NaN,contract,Morson International,Engineering Jobs,370.00 p day,88800,jobsite.co.uk
128340,70087437,Online Agency Sales Manager,A leading consumer media company who have a st...,City of London,The City,full_time,permanent,Digital Gurus,"PR, Advertising & Marketing Jobs",3700 - 35000 per annum + 20k OTE,19350,Brand Republic Jobs
221033,72378463,Project Executive Medical Communications Surrey,Due to organic growth and exciting new busines...,Surrey,Surrey,full_time,permanent,Fresh Connect Recruitment,"PR, Advertising & Marketing Jobs",22000 - 28000 per annum,25000,jobs.newstatesman.com
240843,72668358,Packaging and Labels Sales Representative,Midland Regional Printers Ltd seek an experien...,Nottinghamshire,Nottinghamshire,full_time,permanent,Midland Regional Printers Ltd,Creative & Design Jobs,"25,000 - 29,999",27499,jobs.printweek.com
228079,72445888,Paraplanner,Paraplanner Location: Bristol Salary: **** **...,Bristol Avon South West,UK,NaN,permanent,Heat Recruitment,Accounting & Finance Jobs,"From 20,000 to 30,000 per annum",25000,totaljobs.com
112480,69691217,Java Developer 9 month contract Gtr Manchester,This role will be paid between [blocked]/day s...,Greater Manchester Greater Manchester England,Manchester,NaN,NaN,Computer Futures,IT Jobs,200 -250 per day,54000,gojobsearch.co.uk
86499,69092433,Senior Support Engineer,Key Responsibilities: To provide first class s...,Belfast,Belfast,full_time,permanent,Hays Specialist Recruitment,IT Jobs,30000 - 40000,35000,nijobs.com
148507,70760589,HGV **** Dartford,Due to expansion of our site we urgently requi...,"Dartford, Kent, England, Kent",Dartford,NaN,contract,Interaction Recruitment,Logistics & Warehouse Jobs,9 - 13/hour,21120,cv-library.co.uk
119419,69856724,Financial Analyst,A marvelous opportunity to join a corporate an...,Hertfordshire,Hertfordshire,NaN,permanent,NaN,Logistics & Warehouse Jobs,18-21000,19500,hays.co.uk
127715,70044116,Graduate Technical Assistant,Are you looking to launch your career in Food ...,South East England,South East England,NaN,permanent,D R Newitt,Manufacturing Jobs,20-22K,21000,jobs.foodmanufacture.co.uk
115499,69768354,Venues & Events Consultant,Based in Worcestershire and Gloucestershire . ...,Gloucester,Gloucester,full_time,NaN,E.on UK Plc,Sales Jobs,"12,625.00 - 33,000.00 per year OTE",22812,Jobcentre Plus
77230,69010237,Senior Account Director Global Events,SENIOR ACCOUNT DIRECTOR GLOBAL EVENTS. A SENI...,London,London,NaN,permanent,Creative Personnel,Creative & Design Jobs,60000 - 70000/annum,65000,cv-library.co.uk
90704,69168954,EDistribution Manager,My client a massive player within the insuranc...,Colchester Essex South East,UK,NaN,permanent,Interaction Finance,Accounting & Finance Jobs,75k - 80k per year + Bonus = Benifits,77500,totaljobs.com
15352,66749151,Production Engineer,SRG are working with a leading Medical Device ...,Cirencester,Cirencester,full_time,NaN,srg,Manufacturing Jobs,"30,000.00 - 35,000.00 per year 30000.00 - 3500...",32500,Jobcentre Plus
137238,70407599,Senior Accountant,Mae Lynch is looking to recruit an ambitious S...,Dudley,Dudley,NaN,permanent,Mae Lynch,Accounting & Finance Jobs,35k - 45k per year + benefits,40000,accountancyagejobs.com
72608,68849245,Locality Commissioning Officer,NHS North Derbyshire Clinical Commissioning Gr...,"Derbyshire, High Peak, Derbyshire",High Peak,NaN,contract,NaN,Healthcare & Nursing Jobs,"25,528.00",25528,jobstoday.co.uk
99002,69524509,Food & Beverage Associate (waiter / waitress) ...,Job Type: Full time Permanent Job Description...,"Coldra, Casnewydd (Newport)",UK,NaN,permanent,Celtic Manor Resort,Travel Jobs,Hourly rate - 6.19 p/h,5942,leisurejobs.com
180056,71566161,Java/C Developer,Looking for motivated Java Developers to work ...,Oxfordshire South East,Oxfordshire,NaN,permanent,ISL,IT Jobs,30000 - 50000 per annum + Benefits,40000,cwjobs.co.uk
134370,70253241,Team Administrator,A great opportunity to join a large and well e...,Basingstoke Hampshire South East,Basingstoke,NaN,permanent,On Track Recruitment,Customer Services Jobs,"From 16,000 to 18,000 per annum",17000,totaljobs.com
67263,68718277,Business Development Manager,"As a Business Development Manager, you will us...",East of England,Isle Of Wight,full_time,permanent,EXPERT PATIENT PROGRAMME,Sales Jobs,"30,000 - 36,000",33000,jobs.guardian.co.uk
132792,70227949,Adults | Occupational Therapist | Rochdale,Adults | Occupational Therapist | Rochdale Cur...,North West of the UK,UK,NaN,NaN,4Social Work,Social work Jobs,24.50ph,47040,jobs.communitycare.co.uk
209322,72170370,Child Protection | Qualified Social Worker | S...,Child Protection | Qualified Social Worker | S...,"Greater Manchester, Essex",UK,NaN,NaN,4Social Work,Social work Jobs,24.00ph,46080,jobs.communitycare.co.uk
161234,71188835,New Business / Block Management / South London...,New Business / Block Management / South London...,"Croydon, Surrey Surrey South East",UK,NaN,permanent,TemplePM,Other/General Jobs,"From 26,000 to 40,000 per annum",33000,totaljobs.com
31542,68082397,Weekend Care Assistant Bognor Regis and surro...,"Carer ‘I love being able to help others, no ma...",Bognor Regis West Sussex South East,Bognor Regis,NaN,permanent,Saga Homecare,Healthcare & Nursing Jobs,From 7.50 to 10 per hour,16800,totaljobs.com
213274,72235637,"Charity Fundraiser Full/PartTime Shifts, Flex...",WE ARE LOOKING FOR CHARITY FUNDRAISERS TO STAR...,London South East,South East London,NaN,NaN,Home Fundraising Ltd,Sales Jobs,20000 to 22000 per annum + Benefits Basic plus...,21000,salestarget.co.uk
69621,68806466,Technical Sales Manager Rail UK,Technical Sales Manager (Electronics) Selling ...,Stockport,Stockport,NaN,permanent,Huxley Associates London,Logistics & Warehouse Jobs,"40k - 45k pa + car, pension, bonus, healthcare",42500,jobsite.co.uk
80073,69020519,Deputy Manager,"Deputy Manager, Corby, Northamptonshire We re ...","Corby, Northamptonshire",Corby,NaN,permanent,Game Retail Ltd,Retail Jobs,15000 - 17000/annum plus benefits,16000,cv-library.co.uk
165304,71291619,Senior Finance Business Partner,Our Client is a large service business. A rece...,Hampshire,Hampshire,NaN,permanent,Chilworth Partnership,Accounting & Finance Jobs,60k + car allowance + benefits,60000,accountancyagejobs.com

In [18]:
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk

In [19]:
from nltk.util import ngrams
from collections import Counter

In [20]:
jobs_sample['tokenized_strip'] = jobs_sample.apply(lambda row: row['FullDescription'].decode('utf-8').strip(),axis=1)
jobs_sample['tokenized'] = jobs_sample.apply(lambda row: nltk.word_tokenize(row['tokenized_strip']),axis=1)